### ISSUE TITLE
'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by pietronaccari** [musyoka101/Bludit-CMS-Version-3.9.2-Brute-Force-Protection-Bypass-script#1]
Hi I have an error reading my password file, I solved it by changing the code as follows:
...
with open(fname, encoding = "ISO-8859-1") as f:
...

to understand where the code was blocked I modified the exception like this:

except Exception as e:
	print()
	print()
	print("EXCEPTION: ", e)
	print()
	print("USAGE:\n\npython3 bruteforce.py <IP address> <username> <wordlist>")
	print()

**Comment by musyoka101** [comment]
Thanks so much am looking into the problem and will  change the source if necessary. 


I tested the source code before uploading and it worked fine for me

**Comment by becare** [comment]
You can ignore this encoding problem like this:

with open(fname, errors='ignore') as f:

BTW thx for sharing 👍

**Comment by omkar-dsd** [comment]
@musyoka101 Please review the PR. This issue has been resolved.

**Comment by musyoka101** [comment]
A fix has been released
